### ISSUE TITLE
Question: X-Plane configuration

### ISSUE THREAD

**Issue by JoeriSmits** [MaxFerretti/XPlaneConnector#1]
Hi Max,

I tried your package, however, I don't get any data in my C# program. Do I need to configure anything in X-Plane? Perhaps you do have a small demo project to show basic usage? 

Cheers,
Joeri

**Comment by MaxFerretti** [comment]
Hello,
thank you for using my project.
Actually you don't need to configure the DataRef on X-Plane, but you still need to enable the network part.
I think it is in the settings dialog.
By the way, I'm going to include a sample project.

Let me know if you this helps.

**Comment by JoeriSmits** [comment]
Got it working! It was a misconfiguration of ports and settings. Great project! This enables me to get data from the sim without having knowledge of C++.

I have a minor improvement in the README file. I think there should be states that the call of
```connector.Start();``` is necessary in order to receive data.
