### ISSUE TITLE
adding a new dataref.

### ISSUE THREAD

**Issue by georgegohl888** [MaxFerretti/XPlaneConnector#10]
Amazing library!!

How do I add a custom dataref? i'm using the nuget package as I dont know how to use the raw download as a solution. i want engine rpm as shown. it runs fine but the value is always 0?

`                var rpmdataref = new DataRefElement
                {
                    DataRef = "sim/cockpit2/engine/indicators/engine_speed_rpm",
                    Frequency = 5
                };

                connector.Subscribe(rpmdataref, 25, (element, value) =>
                {
                    enginerpm = $"{value}";
                    Log($"{value}");
                });`

**Comment by georgegohl888** [comment]
I now realise that the dataref is an array for example [579.586853,0.,0.,0.,0.,0.,0.,0.] for a single engine a/c. How do I include this in the program? thanks.

**Comment by MaxFerretti** [comment]
Hello,
sorry for the late reply.
You are using it correctly, but if you need an array, you should subscribe to each element individually, adding an array operand at the end.
In your example, you have 8 elements, so you subscribe to your dataref 8 times, for each dataref use:
sim/cockpit2/engine/indicators/engine_speed_rpm[0]
sim/cockpit2/engine/indicators/engine_speed_rpm[1]
sim/cockpit2/engine/indicators/engine_speed_rpm[2]
... and so on

In a later update I will include handling of arrays directly in the project.
Thanks for your patience.
