### ISSUE TITLE
command send and hold/release

### ISSUE THREAD

**Issue by pepelotte** [MaxFerretti/XPlaneConnector#11]
Hello Max,

first i want to say 1000 times thank you for your great work. It made my life a lot easyer!!!

Now to my question. Some planes need to hold the startet switch to run the eingine. How can i start a command an stop a command. maybe there is a new parameter needed like

Xconn.SendCommand(XPlaneConnector.Commands.StartersEngageStarter1, 1) 'Begin switch Starter

Xconn.SendCommand(XPlaneConnector.Commands.StartersEngageStarter1, 0) 'Release switch Starter

function SendCommand(Command, optional HoldReleaseKey Int)

Greetings
Heiko

**Comment by MaxFerretti** [comment]
Hi,
I'm glad you like the library.
For the press&hold issue, you just send the command continuosly.
Here is a very simple example:
There's a button, when you press it the first time it press&hold the Ignite button and when you press it again you release the button.

`    public partial class Form1 : Form
    {
        XPlaneConnector.XPlaneConnector connector;
        CancellationTokenSource igniteTokenSource;

        public Form1()
        {
            InitializeComponent();

            connector = new XPlaneConnector.XPlaneConnector();
            connector.Start();
        }

        private void igniteButton_Click(object sender, EventArgs e)
        {
            if (igniteTokenSource == null)
            {
                igniteTokenSource = new CancellationTokenSource();

                Task.Run(() =>
                {
                    while (!igniteTokenSource.Token.IsCancellationRequested)
                    {
                        connector.SendCommand(XPlaneConnector.Commands.EnginesEngageStarters);
                    }

                    igniteTokenSource = null;
                });
            }
            else
                igniteTokenSource.Cancel();
        }
    }`

I'm using Task to perform it in async, so you are free to do other things while it's pressed.

**Comment by MaxFerretti** [comment]
I just added a new method StartCommand, I hope it helps :)
Refer to the Readme.md for an example.
Feel free to write again if you need help.

**Comment by pepelotte** [comment]
Absolute great! THANK YOU VERY MUCH!

**Comment by pepelotte** [comment]
Hello Max,


i´am writing at the moment on my app and i get an error. it seems that the "unregister"-function does not work. the first register is ok. the first unregister is ok. the second register is ok but on the second unregister it comes an error (exeption) that there are multible registrations. it seems, that the first unregister does not realy unregister. whats my mistake? hope you can read vb.net - code :-)





        Dim DR_ElementINT As New XPlaneConnector.DataRefElement()
        DR_ElementINT.DataRef = "sim/cockpit/electrical/strobe_lights_on"

        'OK
        Xconn.Subscribe(DR_ElementINT, 25, AddressOf DataRevChangedInt)

        'OK
        Xconn.Unsubscribe("sim/cockpit/electrical/strobe_lights_on")

        'OK
        Xconn.Subscribe(DR_ElementINT, 25, AddressOf DataRevChangedInt)

        'CRASH
        Xconn.Unsubscribe("sim/cockpit/electrical/strobe_lights_on")


Greetings
Heiko


 Von:   Max <notifications@github.com> 
 An:   MaxFerretti/XPlaneConnector <XPlaneConnector@noreply.github.com> 
 Kopie:   pepelotte <h.faiss@itdocs.de>, Author <author@noreply.github.com> 
 Gesendet:   26.01.2020 17:32 
 Betreff:   Re: [MaxFerretti/XPlaneConnector] command send and hold/release (#11) 


I just added a new method StartCommand, I hope it helps :)
 Refer to the Readme.md for an example.
 Feel free to write again if you need help.

**Comment by MaxFerretti** [comment]
Hello,
I'm looking into this issue, I'll let you know as soon as possible.

**Comment by MaxFerretti** [comment]
Hi,
I confirm that there was a bug, when unsubscribing the previous DatRef wasn't removed from the list.
I updated the code to fix the bug and also allow multiple instance of the same DataRef.

**Comment by pepelotte** [comment]
Hello Max,


i got a new problem. i subscribe a string dataref to "sim/aircraft/view/acf_descrip".


        Dim DR_ElementSTRING As New XPlaneConnector.StringDataRefElement
        DR_ElementSTRING.DataRef = "sim/aircraft/view/acf_descrip"
        DR_ElementSTRING.StringLenght = 255
        Xconn.Subscribe(DR_ElementSTRING, 25, AddressOf DataRevChangedString)


the first income value is "Fokker F50". If i switch the plane in xplane to a Piper, i get the following events. the event is released after each changed letter and not on the complete change. can you fix that?


and...can you please update then the dll in the NuGet to the latest version?



sim/aircraft/view/acf_descrip --> Pokker F50
sim/aircraft/view/acf_descrip --> Pikker F50
sim/aircraft/view/acf_descrip --> Pipker F50
sim/aircraft/view/acf_descrip --> Pipeer F50
sim/aircraft/view/acf_descrip --> Piperr F50
sim/aircraft/view/acf_descrip --> Piper  F50
sim/aircraft/view/acf_descrip --> Piper PF50
sim/aircraft/view/acf_descrip --> Piper PA50
sim/aircraft/view/acf_descrip --> Piper PA-0
sim/aircraft/view/acf_descrip --> Piper PA-3
sim/aircraft/view/acf_descrip --> Piper PA-34
sim/aircraft/view/acf_descrip --> Piper PA-34 S
sim/aircraft/view/acf_descrip --> Piper PA-34 Se
sim/aircraft/view/acf_descrip --> Piper PA-34 Sen
sim/aircraft/view/acf_descrip --> Piper PA-34 Sene
sim/aircraft/view/acf_descrip --> Piper PA-34 Senec
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G5
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G50
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 f
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 fo
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-p
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-pl
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-pla
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plan
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 1
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.5
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.5x
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.5x (
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.5x (W
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.5x (Wo
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.5x (Wor
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.5x (Work
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.5x (Works
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.5x (Works i
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.5x (Works in
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.5x (Works in v
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.5x (Works in v1
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.5x (Works in v11
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.5x (Works in v11,
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.5x (Works in v11, b
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.5x (Works in v11, bu
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.5x (Works in v11, but
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.5x (Works in v11, but w
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.5x (Works in v11, but wi
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.5x (Works in v11, but wit
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.5x (Works in v11, but with
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.5x (Works in v11, but witho
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.5x (Works in v11, but withou
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.5x (Works in v11, but without
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.5x (Works in v11, but without v
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.5x (Works in v11, but without v1
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.5x (Works in v11, but without v11
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.5x (Works in v11, but without v11-
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.5x (Works in v11, but without v11-s
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.5x (Works in v11, but without v11-sp
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.5x (Works in v11, but without v11-spe
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.5x (Works in v11, but without v11-spec
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.5x (Works in v11, but without v11-speci
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.5x (Works in v11, but without v11-specif
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.5x (Works in v11, but without v11-specifi
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.5x (Works in v11, but without v11-specific
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.5x (Works in v11, but without v11-specific f
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.5x (Works in v11, but without v11-specific fe
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.5x (Works in v11, but without v11-specific fea
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.5x (Works in v11, but without v11-specific feat
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.5x (Works in v11, but without v11-specific featu
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.5x (Works in v11, but without v11-specific featur
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.5x (Works in v11, but without v11-specific feature
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.5x (Works in v11, but without v11-specific features
sim/aircraft/view/acf_descrip --> Piper PA-34 Seneca V w/G500 for X-plane 10.5x (Works in v11, but without v11-specific features)



 Von:   Max <notifications@github.com> 
 An:   MaxFerretti/XPlaneConnector <XPlaneConnector@noreply.github.com> 
 Kopie:   pepelotte <h.faiss@itdocs.de>, Author <author@noreply.github.com> 
 Gesendet:   17.02.2020 23:20 
 Betreff:   Re: [MaxFerretti/XPlaneConnector] command send and hold/release (#11) 


Hi,
 I confirm that there was a bug, when unsubscribing the previous DatRef wasn't removed from the list.
 I updated the code to fix the bug and also allow multiple instance of the same DataRef.

**Comment by MaxFerretti** [comment]
Hello,
I've seen what the problem is, fixing it is not as easy but I plan on
releasing an update to solve it soon.
In the meantime I've updated the nuget package, now the project target both
.Net 4.6 and .Net Core.

I'll write to you as soon as the problem is fixed.

Max


Il giorno dom 8 mar 2020 alle ore 19:40 pepelotte <notifications@github.com>
ha scritto:
