### ISSUE TITLE
Data can not be received when running from remote PC

### ISSUE THREAD

**Issue by fs2realfly** [MaxFerretti/XPlaneConnector#13]
Hi MaxFerretti,
Thanks for your great project!
When I test your program in my remote PC, connection is good, and command can be sent and work well, but the data window displays nothing, is there something wrong with my program?

I only add the IP pointed to my XPlane:

        private XPlaneConnector.XPlaneConnector connector = new XPlaneConnector.XPlaneConnector("192.168.1.105");

Looking forward to your reply soon.

Regards!

Rick

**Comment by MaxFerretti** [comment]
Hello,
are you using the example program, changing the IP address only?
What version of X-Plane are you using?
I just updated the project and the NuGet package also.
It's just a minor update, so I don't think it will fix the issue, but I'm going to check it out as soon as possible.

**Comment by fs2realfly** [comment]
Yes, I am using the example program, and only changed the IP address, my X-Plane version is 11.41.

And I also updated the Nuget package, as expected, doesn't work.

**Comment by fs2realfly** [comment]
I tried to close the windows firewall, it works!!!

**Comment by MaxFerretti** [comment]
I'm glad you could solve it!
Actually firewalls can block data on the local port.
I could suggest you to authorize your application on the firewall rather than disabling it completely.
