### ISSUE TITLE
Setting a String Valve via Dataref

### ISSUE THREAD

**Issue by githubuser212** [MaxFerretti/XPlaneConnector#14]
Hi There. 

Brilliant library! I can set the numerical values no problem. But I'm trying to set a string value and not sure I have the right syntax?

connector.SetDataRefValue(DataRefs.AircraftViewAcfTailnum, "G-ABCD");

I'm getting compiler errors when I try the above.  

**Argument 1: cannot convert from 'XPlaneConnector.StringDataRefElement' to 'XPlaneConnector.DataRefElement**

Please could suggest what might be wrong? I'd appreciate any advice. Thanks

**Comment by MaxFerretti** [comment]
Hello,
the String DataRef is currently under some refactoring, I will take this into consideration and fix it as soon as possible.
Thank you for your feedback.
