### ISSUE TITLE
Arrays

### ISSUE THREAD

**Issue by tmhab** [MaxFerretti/XPlaneConnector#18]
Just checked your project out, looks promising!

How do you handle getting array DataRefs E.g. **sim/flightmodel/position/q** ?

**Comment by fweinrebe** [comment]
I also had to get values from XP11 that is from a dataref with an array.

What you do is to create your own Datref entries in the DataRefs.cs file. You then use "sim/flightmodel/position/q[0]"...  "sim/flightmodel/position/q[1]" etc. depending on which value in the array you need. 

Here is an example:

`public static DataRefElement AircraftGovernor
 {
    get
            {
                return new DataRefElement
                {
                    DataRef = "sim/cockpit2/engine/actuators/governor_on[0]",
                    Units = "bool",
                    Description = "Governor",
                    Frequency = DefaultFrequency
                };
            }
        }`

**Comment by tmhab** [comment]
Thanks for the solution, @fweinrebe. Straight forward to implement.

I can imagine that subscribing to a single array (if that is possible) would have a little less overhead but I am not even close to that being a concern, so this will do nicely!

**Comment by tmhab** [comment]
Closing the issues as @fweinrebe provided a solution.

**Comment by tmhab** [comment]
Also, as I just now discovered, there was already a closed issue regarding arrays: https://github.com/MaxFerretti/XPlaneConnector/issues/4
