### ISSUE TITLE
Getting numeric values

### ISSUE THREAD

**Issue by ikkennigij121** [MaxFerretti/XPlaneConnector#19]
Hello, wonderfull project! 

playing around a bit with it I managed to get a heading to display in a textbox, but I'm still at loss if I wanted to extract the heading value as an int for example.

I used your example 

```
 private void Button1_Click(object sender, EventArgs e)  //clicking this button will start displaying the heading in the textbox
        {
            
                connector.Subscribe(XPlaneConnector.DataRefs.FlightmodelPositionTruePsi, 25, (element, value) => { LogHeading($"{value}"); });
              
        }

private void LogHeading(string text)
        {

            if (InvokeRequired)
                Invoke(new Action(() => LogHeading(text)));
            else
                Heading_box.Text = text; 
```

my understanding is that the actual value I'm looking for is the float in : (element, **value** ) and I've tried 'extracting' it as follows: 

```
connector.Subscribe(XPlaneConnector.DataRefs.FlightmodelPositionTruePsi, 25, (element, value) =>
                {
                    float NumberExtracted = value;

                });
```
but when I try to print it out to console I don't get any returns.

my main code is a bit of a mess as I'm playing around with it, but the gist of it is that I extract the value of heading and send it via serial communication to another computer. For this I understand I'd need to first 'convert' the number to bytes but for that I'd need the number in the first place and that's where I'm stuck. (I've been able to send a number which I defined as an int before so that's not the issue. The issue is getting the value out of the subscribed dataref)

I appologize if i'm saying things which are a bit vague or don't make sense, but I'm learning as I go (not a programmer by trade)

But I do appreciate the effort put into this project!

hoping for a solution, thanks.

**Comment by raysot** [comment]
You're extracting XPlaneConnector.DataRefs.FlightmodelPositionTruePsi instead of Heading info?

**Comment by ikkennigij121** [comment]
> You're extracting XPlaneConnector.DataRefs.FlightmodelPositionTruePsi instead of Heading info?

Not exactly sure what you're saying but getting the fligtmodelpositiontruepsi is the value I need, however I'm at a loss in getting the numeric value because for some reason I'm unable to store the value in an int for example. In short, I want to get the heading data (or whatever data) out of Xplane, then send that data for useage over serial communication.

I already have an understanding of sending a data value over serial communication, but my issue is extracting xplane data, in this  case the heading for example.

I hope this clarifies things

**Comment by MaxFerretti** [comment]
Hello,
the way XPlane works it treats all values as float, so if you need to use int you have to convert it.
You also have to consider you are receiving values in a callback, so check out the scope of your variables.

In the example above:

```
connector.Subscribe(XPlaneConnector.DataRefs.FlightmodelPositionTruePsi, 25, (element, value) =>
                {
                    // value is a float, NumberExtractedAsInterger lives only inside this callback
                    int NumberExtractedAsInteger = Convert.ToInt32(value);

                });
```

Is it any helpful?

**Comment by ikkennigij121** [comment]
> Hello,
> the way XPlane works it treats all values as float, so if you need to use int you have to convert it.
> You also have to consider you are receiving values in a callback, so check out the scope of your variables.
> 
> In the example above:
> 
> ```
> connector.Subscribe(XPlaneConnector.DataRefs.FlightmodelPositionTruePsi, 25, (element, value) =>
>                 {
>                     // value is a float, NumberExtractedAsInterger lives only inside this callback
>                     int NumberExtractedAsInteger = Convert.ToInt32(value);
> 
>                 });
> ```
> 
> Is it any helpful?

thank you for your reply.
I understand that I have to convert them to an int as all of them are floats, so that's not really the issue.

The part where you mention that the values are in a callback isn't 100% clear to me, and I do believe that that's where my issue lies. 
Please find below the code which I have so far, using your example, but this just displays the heading value in a textbox called Heading_box.
I'm aiming to just get the value.

```
namespace WindowsFormsApp1
{
    public partial class Form1 : Form
    {

        private XPlaneConnector.XPlaneConnector connector = new XPlaneConnector.XPlaneConnector();

        SerialPort port;

        public Form1()
        {
            InitializeComponent();
            connector.Start();

            this.FormClosed += new FormClosedEventHandler(Form1_FormClosed);
            
        }
    
        private void XplaneComm_Click(object sender, EventArgs e)
//button to start serial communication and xplane communication
        {
            port = new SerialPort("COM5", 9600);                       //board COM
            port.Open();
            if (port == null)
            {
                connector.Subscribe(XPlaneConnector.DataRefs.FlightmodelPositionTruePsi, 25, (element, value) => { LogHeading($"{value}"); });
            }
        }

  void Form1_FormClosed(object sender, FormClosedEventArgs e)
        {
            if (port != null && port.IsOpen)
            {
                port.Close();
            }
        }
 private void LogHeading(string text)
        {

            if (InvokeRequired)
                Invoke(new Action(() => LogHeading(text)));
            else
                Heading_box.Text = text;
            
        }
}
```
If I want to use only the value of the heading (for example) and send it through serial comms, would I be correct in formatting the code as follows (just took out the click event part) :

```
private void XplaneComm_Click(object sender, EventArgs e)
        {
            port = new SerialPort("COM5", 9600);                       //board COM
            port.Open();
            if (port == null)
            {
                connector.Subscribe(XPlaneConnector.DataRefs.FlightmodelPositionTruePsi, 25, (element, value) => 
                { 
                int NumberExtractedAsInterger =  Convert.ToInt32 (value);
                port.write (NumberExtractedAsInterger, 0, 1);
                 });
         

            }
        }
```

Hope it makes some sense in explaining my issue?

**Comment by MaxFerretti** [comment]
Ok, I see what's happening in your code.
The problem is that the callback happens at a later time than the subscribe.
I think you should call subscribe just once before, for example in the FormLoad event and use a InvokeRequired format like in the LogHeading.

```
        public Form1()
        {
            InitializeComponent();
            connector.Start();
            port = new SerialPort("COM5", 9600);                       //board COM
            port.Open();
            connector.Subscribe(XPlaneConnector.DataRefs.FlightmodelPositionTruePsi, 25, (element, value) => 
                { 
                    int number = Convert.ToInt32(value);
                    SendViaCOM(number);
                 });

            this.FormClosed += new FormClosedEventHandler(Form1_FormClosed);
            
        }

private void SendViaCOM(int value)
{
      if(InvokeRequired)
            Invoke(new Action(() => SendViaCOM(value)));
      else
      {
            if(port != null)
                   port.write(value, 0, 1);
      }
}
```

This way, every time the value changes you receive a callback and send it automatically to COM.
If you want to send it only when you press the button, maybe you should define an empty callback, save the DataRef object and use it's Value property.

```
        private DataRef _myDR;

        public Form1()
        {
            InitializeComponent();
            connector.Start();
            _myDR = XPlaneConnector.DataRefs.FlightmodelPositionTruePsi;

            port = new SerialPort("COM5", 9600);                       //board COM
            port.Open();
            connector.Subscribe(_myDR, 25, (element, value) => 
                {  // EMPTY
                 });

            this.FormClosed += new FormClosedEventHandler(Form1_FormClosed);
            
        }

private void SendViaCOM(int value)
{
      if(InvokeRequired)
            Invoke(new Action(() => SendViaCOM(value)));
      else
      {
            if(port != null)
                   port.write(value, 0, 1);
      }
}

private void XplaneComm_Click(object sender, EventArgs e)
        {
            if (port == null)
            {
                int NumberExtractedAsInterger =  Convert.ToInt32 (_myDR.Value);
                port.write (NumberExtractedAsInterger, 0, 1):
            }
        }
```

Please forgive me if it's a bit rush-coded, this evening I'll try to make a more structured answer.

**Comment by ikkennigij121** [comment]
Dear Mr. Ferretti,  

my intention was indeed to send it through serial continuousely and your code worked wonderfully !

Just for info, the only thing that needed adjusting was the SendViaCom method where the value needed to be converted to bytes to be sent through serial.

Thank you very much for your help and your project!
