### ISSUE TITLE
Querying byte[] type datarefs always returns 0

### ISSUE THREAD

**Issue by Skinner11** [MaxFerretti/XPlaneConnector#2]
Shouldn't it return the byte array elements in the float? Like when asking for "sim/aircraft/view/acf_descrip", I get 0 as return. Any feedback would be appreciated. Everything else works as it should, great project!

**Comment by MaxFerretti** [comment]
Hello,
thank you for using my project.
Actually, by now it returns values as float, but I can update my
DataRefElement
to include the byte array elements or strings directly.
I'm going to give another read to the documentation to handle Datarefs like
acf_descrip better.

Max

2018-02-09 21:37 GMT+01:00 Skinner11 <notifications@github.com>:

**Comment by MaxFerretti** [comment]
Ok, I have to take into account string type datarefs.
I'm updating the code to manage it, I will make it so that existing code
still compiles and run smoothly.
I'll put in the Readme the new syntax.



2018-02-12 14:42 GMT+01:00 Massimiliano Ferretti <m.ferretti@vodafone.it>:

**Comment by Skinner11** [comment]
Great news, thank you. When can we expect it? No need to rush, just asking.

**Comment by MaxFerretti** [comment]
Hello,
I'm currently under development to extend it.
At first I just coded for float values, but now I want to manage all the
supported data types.
Unfortunately I cannot make it completely compatible with the previous
version since I have to change some of the basics data structures.
I hope I will get it online on the next week.

Max

2018-02-15 13:24 GMT+01:00 Skinner11 <notifications@github.com>:

**Comment by Skinner11** [comment]
Bump 
Any news? 😄

**Comment by MaxFerretti** [comment]
Hello,
I'm sorry for the late reply.
It took some time to re-design the connector in order to make it reliable.
I had to make some major change, I'll write everything in the readme.
It should be ready in the next week.



2018-03-30 18:27 GMT+02:00 Skinner11 <notifications@github.com>:

**Comment by MaxFerretti** [comment]
An update to version 1.1 has been released, if you are still using this project.
Now it can handle strings, please refer to readme.md for additional info.
