### ISSUE TITLE
Readme.md is outdated

### ISSUE THREAD

**Issue by BitBarrel** [MaxFerretti/XPlaneConnector#22]
The Readme.md is outdated. For example:

Instead of:
`var connector = new XPlaneConnector();`

It should be:
`XPlaneConnector.XPlaneConnector connector = new XPlaneConnector.XPlaneConnector();`

and

Instead of:
`connector.SendCommand(XPlaneConnector.Commands.ElectricalBattery1On);`

It should be:
`connector.SendCommand(Commands.ElectricalBattery1On);`

**Comment by MaxFerretti** [comment]
Yes, you are right.
The documentation is a bit outdated.
I'll include all the new features in the next weeks.
