### ISSUE TITLE
Feature request: add custom dataRefs

### ISSUE THREAD

**Issue by BitBarrel** [MaxFerretti/XPlaneConnector#23]
Some 3rd party airplanes use custom datarefs. It would be handy if there is a function which takes the dataref as a string so you can use a custom dataref.

**Comment by MaxFerretti** [comment]
Hi,
you can do that just by creating a new DataRef object with your custom string.
Like this:

`var myDR = new DataRefElement
                {
                    DataRef = "your/custom/dataref",
                    Frequency = 5
                };

connector.Subscribe(myDR, myDR.Frequency, (e, v) => {

    Console.WriteLine($"{DateTime.Now:HH:mm:ss.fff} - {e.DataRef} - {v}");
});
`

In the next release I'll make sure to include a shortcut that takes a string directly.

**Comment by BitBarrel** [comment]
Oh nice, thanks!
It would also be handy if it is included in the documentation (readme).

**Comment by BitBarrel** [comment]
How do you write to a custom dataref? SendCommand only accepts a Commands, not a DataRefElement.

**Comment by MaxFerretti** [comment]
Hello,
Yes, commands are just to inform x plane to perform an action.
If you want to write a specific value to a DataRef you can use the connector method SetSetDataRefValue.
It accepts a DataRefElement or a string and the value you want to set.
