### ISSUE TITLE
Set the Autopilot Heading bug...

### ISSUE THREAD

**Issue by raysot** [MaxFerretti/XPlaneConnector#25]
I'm not quite sure how to set the autopilot heading bug. 

Help! :-)

**Comment by MaxFerretti** [comment]
Hello,
the dataref that you can use to set the heading is via the CockpitAutopilotHeadingMag DataRef.
Its description is "The heading to fly (magnetic, preferred) pilot"

**Comment by raysot** [comment]
Please disregard. My code works perfectly. (And so does yours!)

This is a bug in the Avidyne software I'm using which doesn't correctly update the heading bug! Actual flight testing shows that this works as it should.
