### ISSUE TITLE
How to access DataRefs with Array

### ISSUE THREAD

**Issue by BirdyB** [MaxFerretti/XPlaneConnector#30]
Hi,
I'm currently trying to get the Throttle of all Engines via DataRef `DataRefs.FlightmodelEngineENGNThro` according to the DataRef-Plugin it should return some kind of array: 
```
sim/flightmodel/engine/ENGN_thro
[0.252541,0.,0.,0.,0.,0.,0.,0.]
```
Unfortunately I didn't find any way to get these values. The value-field remains empty.
Is there any way to get the array values?

Thank you!

**Comment by BirdyB** [comment]
Just found the old issue, sorry...

**Comment by MaxFerretti** [comment]
I'm glad you could solve the problem! :)

Il giorno ven 13 mag 2022 alle ore 00:39 BirdyB ***@***.***>
ha scritto:
