### ISSUE TITLE
Cannot subscribe to values for engines

### ISSUE THREAD

**Issue by ingvarr-zaag** [MaxFerretti/XPlaneConnector#32]
Hi
Getting values for engines, ie:
sim/cockpit2/engine/indicators/ITT_deg_C
you have to add index of engine to check:
sim/cockpit2/engine/indicators/ITT_deg_C[0].
As DataRefs don't have the indexes, it is impossible to subscribe for such data.

**Comment by MaxFerretti** [comment]
Hi,
you cannot subscribe using the DataRefs class, but you can define your own DataRef like this:

```C#
var itt_deg = new DataRefElement
                {
                    DataRef = "sim/cockpit2/engine/indicators/ITT_deg_C[0]"
                };

```
and then subscribe using your own istance.
