### ISSUE TITLE
Raise event when server connection has been lost

### ISSUE THREAD

**Issue by DocMoebiuz** [MaxFerretti/XPlaneConnector#33]
For MobiFlight it would be nice to have an event when the connection to the sim is not longer available.
Then MobiFlight can inform the user that the connection has been lost.

Maybe there is a socket exception or maybe only the missing datagrams could be an indicator.

**Comment by MaxFerretti** [comment]
Thank you for the suggestion.
It's a feature I'll definetly add in the near future.

**Comment by theperiscope** [comment]
I haven't tried Mobiflight but I have my own plugin for the Elgato Stream Deck that I had to solve similar challenge so I hope this is useful. Using XPlaneConnector the solution I came up with is to use the `LastReceive` property, and check my own internal "last reconnect attempt time" so we don't flood the computer with too many retry attempts. Then, the main work is to save dataref subscriptions, `Stop()`, restore datarefs, and `Start()` to re-connect -- that definitely improved reliability of my X-Plane connectivity; my previous approach was to have a manual re-connect action/button which was less than ideal.

```c#
private static readonly object _lock = new object();
private static DateTime lastReconnectTry = DateTime.MinValue;
public override async Task OnWillAppear(StreamDeckEventPayload args)
{
  lock (_lock)
  {
    // XPlane.Connector is static instance of XPlaneConnector class
    if (XPlane.Connector.LastReceive == DateTime.MinValue || (DateTime.Now - XPlane.Connector.LastReceive).TotalSeconds >= 5)
    {
      if (lastReconnectTry == DateTime.MinValue || (DateTime.Now - lastReconnectTry).TotalSeconds >= 5)
      {
        lastReconnectTry = DateTime.Now;
        var datarefs = new List<DataRefElement>(XPlane.Connector.DataRefs);
        XPlane.Connector.Stop();
        XPlane.Connector.DataRefs.Clear();
        XPlane.Connector.DataRefs.AddRange(datarefs);
        XPlane.Connector.Start();
      }
    }
  }

  SetModelProperties(args);
  await base.OnWillAppear(args);
}
```
