### ISSUE TITLE
(Question) How to get Values from float array

### ISSUE THREAD

**Issue by mboracing** [MaxFerretti/XPlaneConnector#35]
Hello :-)

I try to get the value DataRefs.Cockpit2EngineIndicatorsPropSpeedRpm just like

`            connector.Subscribe(DataRefs.Cockpit2EngineIndicatorsPropSpeedRpm, 5, (element, value) =>
            {
                Log($"{element.DataRef}: {value}");
            });
`

But the value is always 0. I readed that this DataRef is a float array of 8, could this be the problem and if yes, how to handle?

Cheerio

**Comment by MaxFerretti** [comment]
As for now you have to subscribe to each component of the array individually.
Using the [] format, so basically you have to define your own DataRefs that have the same path but ends with [0], [1].... [8] and subscribe to everyone of them.
I'll ass support for float arrays in the next version.
