### ISSUE TITLE
(Question) Check for connection

### ISSUE THREAD

**Issue by maduranma** [MaxFerretti/XPlaneConnector#36]
Hi.

I'm in the situation I've started a connection; then I turn off X-Plane and turn it back on.

The program still thinks it is connected but in fact it is not, and I don't see any method to check it and try reconnecting.

Thanks in advance!

**Comment by MaxFerretti** [comment]
Thank you for your feedback.
Indeed the connector is not checking for the connection status.
I'll add it in the next version.
