### ISSUE TITLE
Adding custom commands

### ISSUE THREAD

**Issue by pedrobibi** [MaxFerretti/XPlaneConnector#37]
Hi Max,

Maybe you have explained before, but I can't find how to add custom commands to the connector.

In this case I'm searching for Zibo commands.

Regards

**Comment by fweinrebe** [comment]
Hi,

look in the file: Commands.cs  It is in the XPlaneConnector.DataRefs folder.
https://github.com/MaxFerretti/XPlaneConnector/blob/master/XPlaneConnector/XPlaneConnector.DataRefs/Commands.cs

You can add your own references to existing XP commands there.  

E.g.
To define a command "MyZeroAltitude" that executes "sim/Zibo/cockpit/set_alt_to_zero" on XP you define it like this:

`public static XPlaneCommand MyZeroAltitude { get { return new XPlaneCommand("sim/Zibo/cockpit/set_alt_to_zero", "My own description here."); } }`

Note: "sim/Zibo/cockpit/set_alt_to_zero" is just an example, not a real command.

**Comment by MaxFerretti** [comment]
Yes, that is correct.
You can also just simply define a new local variable:
`var myCommand = new XPlaneCommand("sim/Zibo/cockpit/set_alt_to_zero", "My own description here.");`

and use it directly.
