### ISSUE TITLE
Datarefs Array

### ISSUE THREAD

**Issue by pedrobibi** [MaxFerretti/XPlaneConnector#4]
Hello,

First of all, let me say that I'm a newbie on programation.

The question, I see isn't possible to use Array Datarefs, I'm right or there is a solution for this?

An example of which datarefs I'm talking is "sim/flightmodel/engine/ENGN_ITT_c" as a float[]

If isn't possible, could be possible in a future?

Thanks in advance

**Comment by MaxFerretti** [comment]
Hello,
you are right, in the current version you cannot subscribe directly to a float array dataref.
I will probably add this feature in the near future.
As for now, you can workaround this limitation by subscribing to each item individually.

For example, providing you have 2 elements in the arrays, you should subscribe to
sim/flightmodel/engine/ENGN_ITT_c[0]
sim/flightmodel/engine/ENGN_ITT_c[1]
as individual DataRef.

**Comment by pedrobibi** [comment]
First of all, thanks a lot for your answer...

Second, how?

Because prior to write you, I've tested in this way and gives me an error in compilation :-(

it don't accept the brackets []

Sorry to bother you, but I can't follow with my programm without this

Regards and again thanks

**Comment by MaxFerretti** [comment]
Yes, in this case you can't rely on my DataRefs class but you have to create a new instance like this:

```
var engn0= new DataRefElement
                {
                    DataRef = "sim/flightmodel/engine/ENGN_ITT_c[0]",
                    Frequency = 5
                };
var engn1= new DataRefElement
                {
                    DataRef = "sim/flightmodel/engine/ENGN_ITT_c[1]",
                    Frequency = 5
                };

connector.Subscribe(engn0, myDR.Frequency, (element, value) => { /* Your code */});
connector.Subscribe(engn1, myDR.Frequency, (element, value) => { /* Your code */});
```

**Comment by pedrobibi** [comment]
Max, you're my hero...!!

Thanks a lot again for your help, now everything works as expected :-)

Best regards

**Comment by MaxFerretti** [comment]
You're welcome :)
