### ISSUE TITLE
Support to XP build-in functions

### ISSUE THREAD

**Issue by akikettu** [MaxFerretti/XPlaneConnector#5]
Hi!

X-Plane has some build-in functions ("routines") described in https://developer.x-plane.com/sdk/plugin-sdk-documents/

Are those somehow accessible through XPlaneConnector. Example I'd like to convert coordinates to X-Plane compatible format so I would need XPLMWorldToLocal routine (
https://developer.x-plane.com/sdk/XPLMWorldToLocal/).

Regards, Aki

**Comment by MaxFerretti** [comment]
Hello,
unfortunately you cannot access to routines via UDP datagrams.
You can only access to DataRefs and send Commands.
To access to those APIs you have to write a plugin, that's an entirely different approach that requires the usage of C/C++.

**Comment by akikettu** [comment]
Ok. Then I have to suggest this kind of support to UDP from Laminar. I guess UDP protocol itself doesn't prevent this kind of functions.

Closing issue as it's then something can't be done (at least yet...).

Thanks again Max for quick reply! Happy holidays!
