### ISSUE TITLE
Receiving command callbacks from the XPlane?

### ISSUE THREAD

**Issue by jesst3r** [MaxFerretti/XPlaneConnector#6]
Greetings!
Is that possible to receive callbacks on the client side, just like Subscribe, when certain command inside of the XPlane has envoked?
Thanks!

**Comment by MaxFerretti** [comment]
Hello,
it depends on the command you are interested in.
There must be a DataRef associated.
Once you subscribe to a DataRef XPlane continuosly sends the data several times per second, the Connector filters those messages and invokes the callback only when the data changes.
What command are you interested in?

**Comment by jesst3r** [comment]
Max, thank you for your reply:)
For example, i want to track when certain command is invoked, let's take Zibo 737, for example.
There are command "laminar/B738/button/fmc1_exec", and i want to track it out, somehow :/

**Comment by MaxFerretti** [comment]
Hello,
sorry for the late reply.
In my version of DataRefs and Commands I cannot find the command you are referencing to.
Maybe it's an addon plane?
In general I think there should be a corresponding DataRef that gives you a Boolean value that represent the state of the command.
You should then subscribe to that DataRef.
For example: 
For those commands:
sim/lights/nav_lights_on                           Nav lights on.
sim/lights/nav_lights_off                          Nav lights off.
You can subscribe to:
sim/cockpit/electrical/nav_lights_on	int	y	bool	Navigation Light

With this you can be aware of the state of the Navigation lights.
