### ISSUE TITLE
This project is great!

### ISSUE THREAD

**Issue by chbacheng** [MaxFerretti/XPlaneConnector#7]
I hope to continue to update and adapt to the latest version of x-plane

**Comment by MaxFerretti** [comment]
Thank you for your comment!
I will do my best to keep the project updated.
You can always subscribe to newer DataRefs even if they are still not been added "officially".

**Comment by chbacheng** [comment]
I have a problem now. The connection will break after a long time.

**Comment by MaxFerretti** [comment]
Are you receiving and excption from the connector?
In that case, could you send me the Exception Message and StackTrace?
I will soon improve the log event to trace errors.
