### ISSUE TITLE
[Question] Can we modify position or fuel?

### ISSUE THREAD

**Issue by byjokese** [MaxFerretti/XPlaneConnector#8]
Is there any command or way to modify the fuel quantity or aircraft position?
Thanks for the great project!

**Comment by MaxFerretti** [comment]
Hello,
you can modify the aircraft position by setting those 2 datarefs:
sim/flightmodel/position/latitude	        double	n	degrees	The latitude of the aircraft
sim/flightmodel/position/longitude	double	n	degrees	The longitude of the aircraft

About fuel quantity, I think you can do it with this dataref:
sim/aircraft/weight/acf_m_fuel_tot  	float	        y	lbs	Weight of total fuel - appears to be in lbs.

**Comment by byjokese** [comment]
Great, thanks for the datarefs. I didnt see the `SetDataRefValue`. Thanks!

**Comment by Spicy-Bread** [comment]
@byjokese Did you ever find out if you could reposition the aircraft? It is looking like it isn't possible according to this link https://developer.x-plane.com/article/movingtheplane/
