### ISSUE TITLE
Writing custom datarefs?

### ISSUE THREAD

**Issue by pedrobibi** [MaxFerretti/XPlaneConnector#9]
Hi Max,

It's me again :-)

Last time you helped me to add Datarefs Arrays, now I need to know how to "write" a Dataref, I mean, how to change the value in a custom Dataref?

Maybe the methode SetDataRefValue? and how?

Again thank you for your work and help.

Pedro

**Comment by MaxFerretti** [comment]
Hello,
yes, you can write a DataRef value using the SetDataRefValue method.
To se the value just call SetDataRefValue using the DataRef as your first parameter and the new value as second parameter.
If the dataref you want to change is among the DataRefs already coded inside the connector you can use this, if it's a custom dataref, or maybe a newer dataref that isn't in the connector yer, you can simply pass the DataRef name as a string.

**Comment by pedrobibi** [comment]
Max,
Thanks for your help, but no way...
This is what I did:
creating the custom Dataref - OK:

            _var extpwr = new DataRefElement
            {
                DataRef = "Aircraft/Cockpit/Overhead/ElecExt",
                Frequency = 5
            };_

subscribing - OK:

            _connector.Subscribe(extpwr, 100, (e, v) => { externalPwr = v; });_

writing it - NOT OK:

        _private void button1_MouseDown(object sender, MouseEventArgs e)
        {
            connector.SetDataRefValue(extpwr, 1);
        }_

the "extpwr" gives an error that says: "do not exists on the current context"

Sorry to bother you, but I don't know how to follow trying, I have tried in "all possible" ways that I "know" and still not working

Don't forget I'm an awful newbie programmer :-(

Regards

**Comment by MaxFerretti** [comment]
Hi, 
sorry for the late reply.
I think it's a problem related to thread concurrency.
Where do you define extpwr?
I'll try to replicate your error in my environment and then guide you to the correct solution.
If needed I'll update the connector.

**Comment by pedrobibi** [comment]
Hi Max,

First of all, again thank you for your help...

So, below is the "complete test program" I did, to test it.

The Dataref is from an specific airplane (FlightFactor A320) and I've
tested directly in the DataRef Editor plugin and works as expected. 

Ahhh...!! I've changed the name of "_extpwr"_ for "_a320extpwr"_

********************************************** 
_using System;_
_ using System.Collections.Generic;_
_ using System.ComponentModel;_
_ using System.Data;_
_ using System.Drawing;_
_ using System.Linq;_
_ using System.Text;_
_ using System.Threading;_
_ using System.Threading.Tasks;_
_ using System.Windows.Forms;_
_ using System.Globalization;_
_ using XPlaneConnector;_

_ namespace SimujabsA320_
_ {_
_ public partial class frmA320 : Form_
_ {_
_ public static float a320ExtPower = 0;_

_ public frmA320()_
_ {_
_ CheckForIllegalCrossThreadCalls = false;_
_ Thread.CurrentThread.CurrentCulture = new CultureInfo("en-US");_
_ InitializeComponent();_
_ }_

_ //connecting_
_ public static XPlaneConnector.XPlaneConnector connector = new
XPlaneConnector.XPlaneConnector("127.0.0.1", 49000);_

_ public void connectXplane()_
_ {_
_ var engnITT1 = new DataRefElement_
_ {_
_ DataRef = "sim/flightmodel/engine/ENGN_ITT_c[0]",_
_ Frequency = 5_
_ };_
_ var engnITT2 = new DataRefElement_
_ {_
_ DataRef = "sim/flightmodel/engine/ENGN_ITT_c[1]",_
_ Frequency = 5_
_ };_
_ var a320extpwr = new DataRefElement_
_ {_
_ DataRef = "MOKNY/FFA320/Aircraft/Cockpit/Overhead/ElecExt/Target",_
_ Frequency = 5_
_ };_

_ try_
_ {_
_ connector.Start();_
_ }_
_ catch (Exception)_
_ {_
_ MessageBox.Show("Could not connect to XPlaneConnector", "ERROR",
MessageBoxButtons.OK, MessageBoxIcon.Error);_
_ connector.Stop();_
_ return;_
_ }_

_ //subscribing_
_ connector.Subscribe(engnITT1, 100, (e, v) => { ITT1eng});_
_ connector.Subscribe(engnITT2, 100, (e, v) => { ITT2eng});_
_ connector.Subscribe(a320extpwr, 100, (e, v) => { a320ExtPower = v;
});_
_ }_

_ //testing datarefs_
_ private void button1_MouseDown(object sender, MouseEventArgs e)_
_ {_
_if (a320ExtPower == 0)_
_ {_
_ a320ExtPower = 1;_
_ label1.Text = a320ExtPower.ToString();_
_ }_
_ }_

_ private void button1_MouseUp(object sender, MouseEventArgs e)_
_ {_
_ a320ExtPower = 0;_
_ label1.Text = a320ExtPower.ToString();_
_ }_
_ }_
_ }_

*************************************************** 

Best Regards 

Pedro Bibiloni

**Comment by pedrobibi** [comment]
Hi Max,

I don't want to bother you, but... any answer about?

Thank you

**Comment by MaxFerretti** [comment]
Hi Pedrobibi,
first of all sorry for the no-response.
I'm digging into it right now.
Just a quick question, on these lines:
 connector.Subscribe(engnITT1, 100, (e, v) => { ITT1eng });
 connector.Subscribe(engnITT2, 100, (e, v) => { ITT2eng });
What do you mean with ITT1eng and ITT2eng?
I don't find the definition of there statements.

**Comment by pedrobibi** [comment]
Hi Max,
These are the datarefs for the Engine Temperature (something similar like the EGT)
First I declare it as a "custom array" dataref, as you learn me long time ago:

            var engnITT0 = new DataRefElement
            {
                DataRef = "sim/flightmodel/engine/ENGN_ITT_c[0]",
                Frequency = 5
            };

Then, I subscribe to it:

connector.Subscribe(engnITT1, 100, (e, v) => { ITT1eng });

And it works...!!!

**Comment by MaxFerretti** [comment]
Yes, I got it about the DataRef part, I mean the ITT1eng statement.
In particular the lambda expression (e,v) => { ITT1eng }
I can't find a definition for ITT1eng.

**Comment by pedrobibi** [comment]
ahhh... I see...!!!

Sorry, was deleted by me, to avoid confussion, but seems I have confused you more :-)

This is the code for test:

`using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Globalization;
using XPlaneConnector;

namespace SimujabsA320
{
    public partial class frmA320 : Form
    {
        public static float a320ExtPower = 0;

        public frmA320()
        {
            CheckForIllegalCrossThreadCalls = false;
            Thread.CurrentThread.CurrentCulture = new CultureInfo("en-US");
            InitializeComponent();

            label1.Text = a320ExtPower.ToString();
        }

        public static XPlaneConnector.XPlaneConnector connector = new XPlaneConnector.XPlaneConnector("127.0.0.1", 49000);

        public void connectXplane()
        {

            // ********   custom datarefs  *************

            var a320extpwr = new DataRefElement
            {
                DataRef = "MOKNY/FFA320/Aircraft/Cockpit/Overhead/ElecExt/Target", Frequency = 5
            };

            try
            {
                connector.Start();
            }
            catch (Exception)
            {
                MessageBox.Show("Could not connect to XPlaneConnector", "ERROR", MessageBoxButtons.OK, MessageBoxIcon.Error);
                connector.Stop();
                return;
            }

            // *********  subscriptions  ******************

            connector.Subscribe(a320extpwr, 100, (e, v) => { a320ExtPower = v; });

        }

        //  ***********  test button ******************

        private void button1_MouseDown(object sender, MouseEventArgs e)
        {
            connector.SetDataRefValue(a320extpwr, 1);

            if (a320ExtPower == 0)
            {
                a320ExtPower = 1;

                label1.Text = a320ExtPower.ToString();
            }
        }

        private void button1_MouseUp(object sender, MouseEventArgs e)
        {
            connector.SetDataRefValue(a320extpwr, 0);

            a320ExtPower = 0;

            label1.Text = a320ExtPower.ToString();
        }
    }
}`

**Comment by MaxFerretti** [comment]
Hi,
could you try to modify your test program like this?

```
using System;
using System.Threading;
using System.Windows.Forms;
using XPlaneConnector;

namespace Test
{
    public partial class Form1 : Form
    {
        public XPlaneConnector.XPlaneConnector connector = new XPlaneConnector.XPlaneConnector("127.0.0.1", 49000);
        private DataRefElement a320extpwr;

        public void ConnectXplane()
        {
            // ********   custom datarefs  *************

            a320extpwr = new DataRefElement
            {
                DataRef = "MOKNY/FFA320/Aircraft/Cockpit/Overhead/ElecExt/Target",
                Frequency = 5
            };

            try
            {
                connector.Start();
            }
            catch (Exception)
            {
                MessageBox.Show("Could not connect to XPlaneConnector", "ERROR", MessageBoxButtons.OK, MessageBoxIcon.Error);
                connector.Stop();
                return;
            }

            // *********  subscriptions  ******************

            connector.Subscribe(a320extpwr, 100, (e, v) => { SetLabel(v); });
        }

        private void SetLabel(float value)
        {
            if(InvokeRequired)
                Invoke(new Action(() => { SetLabel(value); }));
            else
                label1.Text = $"{DateTime.Now} - v: {value:0}";
        }

        public Form1()
        {
            CheckForIllegalCrossThreadCalls = false;
            Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("en-US");
            InitializeComponent();

            label1.Text = "Waiting...";
            ConnectXplane();
        }

        private void Button1_MouseUp(object sender, MouseEventArgs e)
        {
            connector.SetDataRefValue(a320extpwr, 0);
        }

        private void Button1_MouseDown(object sender, MouseEventArgs e)
        {
            connector.SetDataRefValue(a320extpwr, 1);
        }
    }
}

```

**Comment by pedrobibi** [comment]
Great Max,

 

It Works…!!!

 

I’m really grateful with you…!!!

 

Thanks a lot, as I said previously, I’m sooooo bad programming ☹

 

Regards

 

Saludos

Pedro Bibiloni

 

De: Max <notifications@github.com> 
Enviado el: martes, 24 de septiembre de 2019 14:54
Para: MaxFerretti/XPlaneConnector <XPlaneConnector@noreply.github.com>
CC: pedrobibi <pedrobibi@simujabs.com>; Author <author@noreply.github.com>
Asunto: Re: [MaxFerretti/XPlaneConnector] Writing custom datarefs? (#9)

 

Hi,
could you try to modify your test program like this?

using System;
using System.Threading;
using System.Windows.Forms;
using XPlaneConnector;
 
namespace Test
{
    public partial class Form1 : Form
    {
        public XPlaneConnector.XPlaneConnector connector = new XPlaneConnector.XPlaneConnector("127.0.0.1", 49000);
        private DataRefElement a320extpwr;
 
        public void ConnectXplane()
        {
            // ********   custom datarefs  *************
 
            a320extpwr = new DataRefElement
            {
                DataRef = "MOKNY/FFA320/Aircraft/Cockpit/Overhead/ElecExt/Target",
                Frequency = 5
            };
 
            try
            {
                connector.Start();
            }
            catch (Exception)
            {
                MessageBox.Show("Could not connect to XPlaneConnector", "ERROR", MessageBoxButtons.OK, MessageBoxIcon.Error);
                connector.Stop();
                return;
            }
 
            // *********  subscriptions  ******************
 
            connector.Subscribe(a320extpwr, 100, (e, v) => { SetLabel(v); });
        }
 
        private void SetLabel(float value)
        {
            if(InvokeRequired)
                Invoke(new Action(() => { SetLabel(value); }));
            else
                label1.Text = $"{DateTime.Now} - v: {value:0}";
        }
 
        public Form1()
        {
            CheckForIllegalCrossThreadCalls = false;
            Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("en-US");
            InitializeComponent();
 
            label1.Text = "Waiting...";
            ConnectXplane();
        }
 
        private void Button1_MouseUp(object sender, MouseEventArgs e)
        {
            connector.SetDataRefValue(a320extpwr, 0);
        }
 
        private void Button1_MouseDown(object sender, MouseEventArgs e)
        {
            connector.SetDataRefValue(a320extpwr, 1);
        }
    }
}

**Comment by MaxFerretti** [comment]
Great!
I'm happy I could solve your issue.
If you need anything else feel free to write again.
